### ISSUE TITLE
why a FullScreen control object is not an instance of ol.control.Control

### ISSUE THREAD

**Issue by scil** [ghettovoice/vuelayers#495]
I add a FullScreen control.
```
<template>
  <div>
    <vl-map ref="map" :load-tiles-while-animating="true"
            :load-tiles-while-interacting="true"
            :defaultControls="false"
            data-projection="EPSG:4326"
            style="height: 400px" @created="mapCreated" >

    </vl-map>
  </div>
</template>

<script>



import {FullScreen,  } from 'ol/control'

export default {
  methods: {

    mapCreated(vm) {
      this.fullScreenControl = new FullScreen()
      vm.$map.addControl(this.fullScreenControl)
    },

  }
}
```

error:
```
vue.runtime.esm.js:619 [Vue warn]: Error in getter for watcher "controls": "Error: Illegal control argument"

found in

---> <VlMap>
       <OlMap> at Assets/vue/components/vuelayers-map.vue
         <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1893
globalHandleError @ vue.runtime.esm.js:1888
handleError @ vue.runtime.esm.js:1848
get @ vue.runtime.esm.js:4498
run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
queueWatcher @ vue.runtime.esm.js:4418
update @ vue.runtime.esm.js:4560
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4644
_callee15$ @ mixins.js:1079
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
changed @ mixins.js:1089
flush @ index.js:54
setTimeout (async)
debounced @ index.js:38
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext @ mergeMap.js:85
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/innerSubscribe.js.SimpleInnerSubscriber._next @ innerSubscribe.js:14
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next @ map.js:41
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
handler @ fromEventPattern.js:16
push../node_modules/vuelayers/node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:118
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.notify @ Object.js:185
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.set @ Object.js:218
push../node_modules/vuelayers/node_modules/ol/PluggableMap.js.PluggableMap.setView @ PluggableMap.js:1374
setView @ vuelayers.esm.js:8773
_callee2$ @ vuelayers.esm.js:7059
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mount @ vuelayers.esm.js:7068
_callee17$ @ mixins.js:1446
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_execMount @ mixins.js:1489
execMount @ mixins.js:1396
_callee2$ @ mixins.js:516
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ mixins.js:524
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
invokeInsertHook @ vue.runtime.esm.js:6390
patch @ vue.runtime.esm.js:6609
Vue._update @ vue.runtime.esm.js:3960
updateComponent @ vue.runtime.esm.js:4081
get @ vue.runtime.esm.js:4495
Watcher @ vue.runtime.esm.js:4484
mountComponent @ vue.runtime.esm.js:4088
__webpack_modules__../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8459
(anonymous) @ Tian.html:330
Promise.then (async)
(anonymous) @ Tian.html:328
load (async)
addOnload @ Tian.html:15
(anonymous) @ Tian.html:326
Show 29 more frames
vue.runtime.esm.js:1897 Error: Illegal control argument
    at getControlId (ol-ext.js:44:1)
    at vuelayers.esm.js:8050:27
    at utils.js:372:1
    at utils.js:345:1
    at forEach (utils.js:337:1)
    at reduce (utils.js:344:1)
    at map (utils.js:371:1)
    at VueComponent.controls (vuelayers.esm.js:8048:19)
    at Watcher.get (vue.runtime.esm.js:4495:1)
    at Watcher.evaluate (vue.runtime.esm.js:4597:1)
logError @ vue.runtime.esm.js:1897
globalHandleError @ vue.runtime.esm.js:1888
handleError @ vue.runtime.esm.js:1848
get @ vue.runtime.esm.js:4498
run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
queueWatcher @ vue.runtime.esm.js:4418
update @ vue.runtime.esm.js:4560
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4644
_callee15$ @ mixins.js:1079
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
changed @ mixins.js:1089
flush @ index.js:54
setTimeout (async)
debounced @ index.js:38
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext @ mergeMap.js:85
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/innerSubscribe.js.SimpleInnerSubscriber._next @ innerSubscribe.js:14
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next @ map.js:41
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
handler @ fromEventPattern.js:16
push../node_modules/vuelayers/node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:118
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.notify @ Object.js:185
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.set @ Object.js:218
push../node_modules/vuelayers/node_modules/ol/PluggableMap.js.PluggableMap.setView @ PluggableMap.js:1374
setView @ vuelayers.esm.js:8773
_callee2$ @ vuelayers.esm.js:7059
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mount @ vuelayers.esm.js:7068
_callee17$ @ mixins.js:1446
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_execMount @ mixins.js:1489
execMount @ mixins.js:1396
_callee2$ @ mixins.js:516
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ mixins.js:524
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
invokeInsertHook @ vue.runtime.esm.js:6390
patch @ vue.runtime.esm.js:6609
Vue._update @ vue.runtime.esm.js:3960
updateComponent @ vue.runtime.esm.js:4081
get @ vue.runtime.esm.js:4495
Watcher @ vue.runtime.esm.js:4484
mountComponent @ vue.runtime.esm.js:4088
__webpack_modules__../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8459
(anonymous) @ Tian.html:330
Promise.then (async)
(anonymous) @ Tian.html:328
load (async)
addOnload @ Tian.html:15
(anonymous) @ Tian.html:326
Show 28 more frames
vue.runtime.esm.js:619 [Vue warn]: Error in callback for watcher "controls": "TypeError: Cannot read properties of undefined (reading 'slice')"

found in

---> <VlMap>
       <OlMap> at Assets/vue/components/vuelayers-map.vue
         <Root>
warn @ vue.runtime.esm.js:619
logError @ vue.runtime.esm.js:1893
globalHandleError @ vue.runtime.esm.js:1888
handleError @ vue.runtime.esm.js:1848
invokeWithErrorHandling @ vue.runtime.esm.js:1871
run @ vue.runtime.esm.js:4584
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
queueWatcher @ vue.runtime.esm.js:4418
update @ vue.runtime.esm.js:4560
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4644
_callee15$ @ mixins.js:1079
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
changed @ mixins.js:1089
flush @ index.js:54
setTimeout (async)
debounced @ index.js:38
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber.notifyNext @ mergeMap.js:85
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/innerSubscribe.js.SimpleInnerSubscriber._next @ innerSubscribe.js:14
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next @ map.js:41
push../node_modules/vuelayers/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
handler @ fromEventPattern.js:16
push../node_modules/vuelayers/node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:118
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.notify @ Object.js:185
push../node_modules/vuelayers/node_modules/ol/Object.js.BaseObject.set @ Object.js:218
push../node_modules/vuelayers/node_modules/ol/PluggableMap.js.PluggableMap.setView @ PluggableMap.js:1374
setView @ vuelayers.esm.js:8773
_callee2$ @ vuelayers.esm.js:7059
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mount @ vuelayers.esm.js:7068
_callee17$ @ mixins.js:1446
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_execMount @ mixins.js:1489
execMount @ mixins.js:1396
_callee2$ @ mixins.js:516
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
mounted @ mixins.js:524
invokeWithErrorHandling @ vue.runtime.esm.js:1863
callHook @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
invokeInsertHook @ vue.runtime.esm.js:6390
patch @ vue.runtime.esm.js:6609
Vue._update @ vue.runtime.esm.js:3960
updateComponent @ vue.runtime.esm.js:4081
get @ vue.runtime.esm.js:4495
Watcher @ vue.runtime.esm.js:4484
mountComponent @ vue.runtime.esm.js:4088
__webpack_modules__../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8459
(anonymous) @ Tian.html:330
Promise.then (async)
(anonymous) @ Tian.html:328
load (async)
addOnload @ Tian.html:15
(anonymous) @ Tian.html:326
Show 29 more frames
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'slice')
    at VueComponent.handler (vuelayers.esm.js:8154:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at Watcher.run (vue.runtime.esm.js:4584:1)
    at flushSchedulerQueue (vue.runtime.esm.js:4326:1)
    at Array.<anonymous> (vue.runtime.esm.js:1989:1)
    at flushCallbacks (vue.runtime.esm.js:1915:1)
```

now I located here:

![image](https://user-images.githubusercontent.com/2786775/165882678-ff589f72-f069-4d63-9fe7-b4cead9023d4.png)

```
// ol-ext.js

function getControlId(control) {
    if (control instanceof Control) {
        return control.get('id');
    }

    throw new Error('Illegal control argument');
}

```

the problem :  the object `control` is an instanceof `FullScreen` which is subclass of `Control`.

but why `control instanceof Control`  equals `false`

**Comment by ghettovoice** [comment]
Hello @scil ,
this is probably possible because you have 2 versions of OpenLayers in runtime. For example if you manually install VueLayers and also OpenLayers.
Make sure that you are using openlayers "ol": "^6.4.3 < 6.7.0 || ^6.8.2". This is ol version range from vuelayers package.json.
