### ISSUE TITLE
error occurs when activating the tab which contains vuelayers

### ISSUE THREAD

**Issue by scil** [ghettovoice/vuelayers#535]
fake code
```
<div 
                                <ul class='flex cursor-pointer leading-6'>
                                    <li  @click="activeTab=0">
                                        Text
                                    </li>

                                    <li  @click="activeTab=1">
                                        Map
                                    </li>

                                </ul>
</div>


<div v-show="activeTab===1">
    <vl-map></vl-map>
</div>
```

when activating the second tab 'Map',   error report by console:
![image](https://github.com/ghettovoice/vuelayers/assets/2786775/c9c306cf-6aaa-4814-95b9-28aa42ea20be)

```
vue.esm.js:628 [Vue warn]: Error in beforeDestroy hook (Promise/async): "LifecycleError: VlView.9b2452ca-de05-42eb-8bc8-ac626527edb1 unmount ol object failed: Cannot read properties of null (reading 'getProjection')"

found in

---> <VlView>
       <VlMap>
         <OlMap> at front_end/common/vue/components/ol-map/ol-map.vue
           <SwiperMap> at front_end/common/vue/components/swiper-map.vue
             <FormulateForm>
               <ArticleEdit> at Assets/js/vue/components/article-edit.vue
                 <Root>
warn @ vue.esm.js:628
logError @ vue.esm.js:1902
globalHandleError @ vue.esm.js:1897
handleError @ vue.esm.js:1857
(anonymous) @ vue.esm.js:1874
Promise.catch (async)
invokeWithErrorHandling @ vue.esm.js:1874
callHook @ vue.esm.js:4244
Vue.$destroy @ vue.esm.js:4002
destroy @ vue.esm.js:3187
invokeDestroyHook @ vue.esm.js:6169
invokeDestroyHook @ vue.esm.js:6174
patch @ vue.esm.js:6522
Vue.$destroy @ vue.esm.js:4025
destroy @ vue.esm.js:3187
invokeDestroyHook @ vue.esm.js:6169
invokeDestroyHook @ vue.esm.js:6174
patch @ vue.esm.js:6522
Vue.$destroy @ vue.esm.js:4025
destroy @ vue.esm.js:3187
invokeDestroyHook @ vue.esm.js:6169
invokeDestroyHook @ vue.esm.js:6174
invokeDestroyHook @ vue.esm.js:6174
patch @ vue.esm.js:6522
Vue.$destroy @ vue.esm.js:4025
destroy @ vue.esm.js:3187
invokeDestroyHook @ vue.esm.js:6169
invokeDestroyHook @ vue.esm.js:6174
invokeDestroyHook @ vue.esm.js:6174
removeVnodes @ vue.esm.js:6185
updateChildren @ vue.esm.js:6290
patchVnode @ vue.esm.js:6374
updateChildren @ vue.esm.js:6248
patchVnode @ vue.esm.js:6374
updateChildren @ vue.esm.js:6248
patchVnode @ vue.esm.js:6374
updateChildren @ vue.esm.js:6248
patchVnode @ vue.esm.js:6374
patch @ vue.esm.js:6537
Vue._update @ vue.esm.js:3972
updateComponent @ vue.esm.js:4090
get @ vue.esm.js:4504
run @ vue.esm.js:4579
flushSchedulerQueue @ vue.esm.js:4335
(anonymous) @ vue.esm.js:1998
flushCallbacks @ vue.esm.js:1924
Promise.then (async)
timerFunc @ vue.esm.js:1951
nextTick @ vue.esm.js:2008
queueWatcher @ vue.esm.js:4427
update @ vue.esm.js:4569
notify @ vue.esm.js:739
reactiveSetter @ vue.esm.js:1064
proxySetter @ vue.esm.js:4653
click @ article-edit.vue:260
invokeWithErrorHandling @ vue.esm.js:1872
invoker @ vue.esm.js:2197
original._wrapper @ vue.esm.js:7609

vue.esm.js:1906 VlView.9b2452ca-de05-42eb-8bc8-ac626527edb1 unmount ol object failed: TypeError: Cannot read properties of null (reading 'getProjection')
    at OverviewMap.bindView_ (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:73587:26)
    at OverviewMap.handleMapPropertyChange_ (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:73573:12)
    at Target.dispatchEvent (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:76275:88)
    at BaseObject.notify (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:66054:12)
    at BaseObject.set (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:66086:14)
    at PluggableMap.setView (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:68299:12)
    at VueComponent.setView (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:49681:19)
    at VueComponent.unmount (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:48506:29)
    at VueComponent.execUnmount (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:32252:16)
    at async VueComponent.beforeDestroy (http://192.168.0.1:5111/js/chunk-vendors-node_modules_vuelayers_dist_vuelayers-2abaf8.js:31649:5)
```

**Comment by scil** [comment]
after some step debug, I found that,  openlayers-related code, like  /ol/control/OverviewMap.js has been executed until the Tab 'Map' is shown.

Plus the word `beforeDestroy` in the error msg, so I tried to add `v-if` in the Tab 'Map',  like 
```

<div v-show="activeTab===1" v-if="tab1EverLoaded">
    <vl-map></vl-map>
</div>
```

to make the map not init until the tab is ever clicked.

OK!
